import{a as b,S,i as l}from"./assets/vendor-BBSqv8W6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const q="49627345-81d87c81626646e8cd4c1e6ab",f=async(s,t)=>await b("https://pixabay.com/api/",{params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:"15",page:t}}),h=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".show-more"),M=new S(".gallery-card a",{captionsData:"alt",captionDelay:"250"});function y(s){h.insertAdjacentHTML("beforeend",s.map(({webformatURL:t,largeImageURL:r,tags:a,likes:e,views:o,comments:n,downloads:w})=>`<li class="image-item">
            <div class="gallery-card"><a href="${r}"><img src="${t}" alt="${a}" class="image"/></a></div>
            <ul class="image-info">
                <li>Likes<p>${e}</p></li>
                <li>Views<p>${o}</p></li>
                <li>Comments<p>${n}</p></li>
                <li>Downloads<p>${w}</p></li>
            </ul>
        </li>`).join("")),M.refresh()}const $=()=>{h.innerHTML=""},L=()=>{g.classList.remove("visually-hidden")},u=()=>{g.classList.add("visually-hidden")},C=()=>{p.classList.remove("visually-hidden")},m=()=>{p.classList.add("visually-hidden")},c=document.querySelector(".form"),E=document.querySelector(".show-more");let d=1,v;c.addEventListener("submit",I);E.addEventListener("click",O);function I(s){s.preventDefault(),L(),$(),d=1,console.log(s.currentTarget);const t=c.elements[0].value.toLowerCase().trim();if(!(t.length>0)){l.show(i),u(),c.reset();return}C(),v=t,f(t,d).then(r=>{const a=r.data.hits;if(!a.length){l.show(i),m();return}y(a)}).catch(r=>{i.message=r.message,l.show(i),m()}).finally(()=>{u(),c.reset()})}function O(s){L(),d+=1,f(v,d).then(t=>{const r=t.data.hits;y(r)}).catch(t=>{i.message=t.message,l.show(i)}).finally(()=>{u()})}const i={title:"Error",titleColor:"#fafafb",message:"Sorry, there are no images matching your search query. Please try again!",iconColor:"#fafafb",color:"#ef4040",messageColor:"#fafafb",position:"topRight",messageSize:"16px",messageSize:"150%"};
//# sourceMappingURL=index.js.map
