import{a as I,S as M,i as r}from"./assets/vendor-BBSqv8W6.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const P="49627345-81d87c81626646e8cd4c1e6ab",y=async(a,e=1)=>await I("https://pixabay.com/api/",{params:{key:P,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:"15",page:e}}),w=document.querySelector(".gallery"),L=document.querySelector(".loader"),v=document.querySelector(".show-more"),$=new M(".gallery-card a",{captionsData:"alt",captionDelay:"250"});function p(a){w.insertAdjacentHTML("beforeend",a.map(({webformatURL:e,largeImageURL:o,tags:n,likes:t,views:s,comments:c,downloads:q})=>`<li class="image-item">
            <div class="gallery-card"><a href="${o}"><img src="${e}" alt="${n}" class="image"/></a></div>
            <ul class="image-info">
                <li>Likes<p>${t}</p></li>
                <li>Views<p>${s}</p></li>
                <li>Comments<p>${c}</p></li>
                <li>Downloads<p>${q}</p></li>
            </ul>
        </li>`).join("")),$.refresh()}const B=()=>{w.innerHTML=""},b=()=>{L.classList.remove("visually-hidden")},h=()=>{L.classList.add("visually-hidden")},C=()=>{v.classList.remove("visually-hidden")},u=()=>{v.classList.add("visually-hidden")},m=document.querySelector(".form"),g=document.querySelector(".show-more"),d="save-search";let l=1,f;O(l);m.addEventListener("submit",E);g.addEventListener("click",z);async function E(a){a.preventDefault(),b(),u(),B();const e=m.elements[0].value.toLowerCase().trim();if(e.length<=0){r.show(i),h(),m.reset();return}localStorage.setItem(d,e);try{const{data:o}=await y(e);if(p(o.hits),f=o.totalHits/o.hits.length,!o.hits.length){r.show(i),localStorage.removeItem(d),u();return}l<f&&C(),l===f&&r.show(S)}catch(o){i.message=o.message,r.show(i)}finally{h(),m.reset()}}async function z(a){b(),l++,g.disabled=!0;let e=localStorage.getItem(d);try{const{data:o}=await y(e,l);p(o.hits),l>=f&&(u(),localStorage.removeItem(d),l=1,r.show(S));const t=document.querySelector(".image-item").getBoundingClientRect().height;window.scrollBy({left:0,top:t*2,behavior:"smooth"})}catch(o){i.message=o.message,r.show(i)}finally{h(),g.disabled=!1}}async function O(a){if(localStorage.length>0)try{const{data:e}=await y(localStorage.getItem(d),a);p(e.hits),a<e.totalHits/e.hits.length&&C(),a===e.totalHits/e.hits.length&&r.show(S)}catch(e){i.message=e.message,r.show(i)}}const i={title:"Error",titleColor:"#fafafb",message:"Sorry, there are no images matching your search query. Please try again!",iconColor:"#fafafb",color:"#ef4040",messageColor:"#fafafb",position:"topRight",messageSize:"16px",messageSize:"150%"},S={title:"",titleColor:"#fafafb",message:"We're sorry, but you've reached the end of search results.",iconColor:"#fafafb",color:"#0A8106",messageColor:"#fafafb",position:"topRight",messageSize:"16px",messageSize:"150%"};
//# sourceMappingURL=index.js.map
